### ISSUE TITLE
Week Milestones

### ISSUE THREAD

**Issue by diegocasmo** [diegocasmo/ml-project#18]
@tristaaan @ankurshukla03 

- [x] Review and merge neural networks and deep learning sections (#17) 
- [x] Avoid using 'we' in the report (#17)
- [x] Improve the order of the sections in the report (#21)
- [ ] Implement data augmentation techniques (Tristan and Ankur)
- [x] Include table with a description of each of the layers in the VGG-16 architecture (#17)

**Comment by ankurshukla03** [comment]
@diegocasmo 
more writing in vgg16 section as we need to explain each type block used in vgg16?
